/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-125185-g30155f9c3a-20260623"
#endif /* AVUTIL_FFVERSION_H */
